name: admin-ui-voicemail
namespace: official
version: 1.0.0
author: Wazo Team
display_name: Voicemail
min_wazo_version: 17.16
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-voicemail
